# Generated by Django 3.0.8 on 2020-07-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200728_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='url',
        ),
    ]
